server:
  port: 8888 #不写端口默认8080
  tomcat:
    uri-encoding: utf-8 #编码方式

######################### Druid连接池的配置信息  #################
spring:
  datasource:
    xa:
      data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource  #数据库驱动
    url: jdbc:mysql://localhost:3306/diary?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=America/New_York&useSSL=true
    username: root
    password: liang5200
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat,log4j #配置监控统计拦截的filters，stat wall log4j，去掉后监控界面sql将无法统计,'wall'用于防火墙
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      #测试连接
      validation-query: SELECT 'x'
      #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      test-while-idle: true
      #获取连接时执行检测，建议关闭，影响性能
      test-on-borrow: false
      #归还连接时执行检测，建议关闭，影响性能
      test-on-return: false
      #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      pool-prepared-statements: true
      #开启poolPreparedStatements后生效
      max-pool-prepared-statement-per-connection-size: 20

mybatis:
  configuration:
    #全局映射器启用缓存
    cache-enabled: true
    #查询时,关闭关联对象及时加载以提高性能
    lazy-loading-enabled: false
    #按需加载字段(加载字段由SQL指定),不会加载关联表的所有字段,以提高性能
    aggressive-lazy-loading: false
    #允许返回不同的结果集以达到通用的效果
    multiple-result-sets-enabled: true
    #对于批量更新操作缓存SQL以提高性能
    default-executor-type: reuse
    #数据库执行超时时间
    default-statement-timeout: 25000
  #mapper扫描路径
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.hl.diary.mapper






